name: C/C++ CI

on:
  push:
    branches:
      - "dev"
      - "master"
  pull_request:
    branches:
      - "dev"
      - "master"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libraries
        run: sudo add-apt-repository universe && sudo apt update && sudo apt upgrade && sudo apt install curl && sudo apt-get install libcurl4-openssl-dev libgtest-dev googletest google-mock libgmock-dev libtbb-dev libjsoncpp-dev libgtk-3-dev libwebkit2gtk-4.0-dev nodejs npm
      - name: Building project
        run: mkdir build && cd build && cmake .. && cmake --build .